NUMBER_OF_RECIPES = 100000
VOCAB_SIZE = 15000
MODEL_PATH = f"data/out/blstm_model_{NUMBER_OF_RECIPES}_emb_bert_tokenizer_long"

RECIPE_START_TOKEN = "<RECIPE_START>"
RECIPE_END_TOKEN = " <RECIPE_END>"

TITLE_START_TOKEN = " <TITLE_START> "
TITLE_END_TOKEN = " <TITLE_END>"

NER_START_TOKEN = " <NER_START> "
NER_END_TOKEN = " <NER_END> "
NER_NEXT_TOKEN = " <NER_NEXT> "

INGREDIENTS_START_TOKEN = "<INGREDIENTS_START> "
INGREDIENTS_END_TOKEN = " <INGREDIENTS_END>"
INGREDIENTS_NEXT_TOKEN = " <INGREDIENTS_NEXT> "

INSTRUCTIONS_START_TOKEN = " <INSTRUCTIONS_START>"
INSTRUCTIONS_END_TOKEN = " <INSTRUCTIONS_END>"
INSTRUCTIONS_NEXT_TOKEN = " <INSTRUCTIONS_NEXT>"

MAX_RECIPE_LENGTH = 200
MIN_RECIPE_LENGTH = 100

NEW_TOKENS = [
    RECIPE_START_TOKEN,
    RECIPE_END_TOKEN,
    TITLE_START_TOKEN,
    TITLE_END_TOKEN,
    NER_START_TOKEN,
    NER_END_TOKEN,
    NER_NEXT_TOKEN,
    INGREDIENTS_START_TOKEN,
    INGREDIENTS_END_TOKEN,
    INGREDIENTS_NEXT_TOKEN,
    INSTRUCTIONS_START_TOKEN,
    INSTRUCTIONS_END_TOKEN,
    INSTRUCTIONS_NEXT_TOKEN,
]


RECIPE_START_TOKEN_NO_SPACES = "<RECIPE_START>"
RECIPE_END_TOKEN_NO_SPACES = "<RECIPE_END>"

TITLE_START_TOKEN_NO_SPACES = "<TITLE_START>"
TITLE_END_TOKEN_NO_SPACES = "<TITLE_END>"

NER_START_TOKEN_NO_SPACES = "<NER_START>"
NER_END_TOKEN_NO_SPACES = "<NER_END>"
NER_NEXT_TOKEN_NO_SPACES = "<NER_NEXT>"

INGREDIENTS_START_TOKEN_NO_SPACES = "<INGREDIENTS_START>"
INGREDIENTS_END_TOKEN_NO_SPACES = "<INGREDIENTS_END>"
INGREDIENTS_NEXT_TOKEN_NO_SPACES = "<INGREDIENTS_NEXT>"

INSTRUCTIONS_START_TOKEN_NO_SPACES = "<INSTRUCTIONS_START>"
INSTRUCTIONS_END_TOKEN_NO_SPACES = "<INSTRUCTIONS_END>"
INSTRUCTIONS_NEXT_TOKEN_NO_SPACES = "<INSTRUCTIONS_NEXT>"

NEW_TOKENS_NO_SPACES = [
    RECIPE_START_TOKEN_NO_SPACES,
    RECIPE_END_TOKEN_NO_SPACES,
    TITLE_START_TOKEN_NO_SPACES,
    TITLE_END_TOKEN_NO_SPACES,
    NER_START_TOKEN_NO_SPACES,
    NER_END_TOKEN_NO_SPACES,
    NER_NEXT_TOKEN_NO_SPACES,
    INGREDIENTS_START_TOKEN_NO_SPACES,
    INGREDIENTS_END_TOKEN_NO_SPACES,
    INGREDIENTS_NEXT_TOKEN_NO_SPACES,
    INSTRUCTIONS_START_TOKEN_NO_SPACES,
    INSTRUCTIONS_END_TOKEN_NO_SPACES,
    INSTRUCTIONS_NEXT_TOKEN_NO_SPACES,
]
